# Generated by Django 5.0.2 on 2024-03-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'account_api',
            },
        ),
    ]
